config/routes.rb
Tioj::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :problems do
    resources :testdata
    resources :submissions
    resources :posts 
  end

  resources :judge_servers
  resources :submissions
  resources :users
  resources :posts do 
    resources :comments
  end
  
  resources :contests do
    resources :submissions
    resources :problems
  end
  resources :contest_problem_joints
  
  resources :articles
  
  get 'problems/tag/:tag' => 'problems#index', as: :problems_tag
  get 'problems/:id/ranklist' => 'problems#ranklist', as: :problem_ranklist
  
  get 'contests/:id/set_contest_task/:alter_to' => 'contests#set_contest_task', as: :set_contest_task
  get 'contests/:id/dashboard' => 'contests#dashboard'
  get 'submissions/:id/rejudge' => 'submissions#rejudge'
  get 'problems/:problem_id/rejudge' => 'submissions#rejudge_problem', as: :problem_rejudge
  
  get 'fetch/sjcode' => 'fetch#sjcode'
  get 'fetch/code' => 'fetch#code'
  get 'fetch/interlib' => 'fetch#interlib'
  get 'fetch/testdata' => 'fetch#testdata'
  get 'fetch/submission' => 'fetch#submission'
  get 'fetch/validating' => 'fetch#validating'
  get 'fetch/write_result' => 'fetch#write_result'
  post 'fetch/write_message' => 'fetch#write_message'
  get 'fetch/testdata_limit' => 'fetch#testdata_limit'
  get 'fetch/testdata_meta' => 'fetch#testdata_meta'
  
  mathjax 'mathjax'
  
  get 'edit_announcement' => 'welcome#edit_announcement', as: :edit_announcement
  post 'alter_announcement' => 'welcome#alter_announcement', as: :alter_announcement
  get 'about' => 'about#index', as: :about

  get 'problems/:id/*file' => redirect{ |path, req| "/#{path[:file]}"}, :format => false, :id => /[0-9]+/
  get 'problems/*file' => redirect{ |path, req| "/#{path[:file]}"}, :format => false

  root 'welcome#index'

end

app/models/contest.rb
# == Schema Information
#
# Table name: contests
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  description  :text(65535)
#  start_time   :datetime
#  end_time     :datetime
#  contest_type :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Contest < ActiveRecord::Base
  has_many :contest_problem_joints, :dependent => :destroy
  has_many :problems, :through => :contest_problem_joints
  has_many :submissions

  validates :start_time, :presence => true
  validates :end_time, :presence => true

  accepts_nested_attributes_for :contest_problem_joints, :reject_if => lambda { |a| a[:problem_id].blank? }, :allow_destroy => true
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_filter :authenticate_admin!, except: [:dashboard, :index, :show]
  before_filter :set_contest, only: [:show, :edit, :update, :destroy, :dashboard, :set_contest_task]
  before_filter :set_tasks, only: [:show, :dashboard, :set_contest_task]
  layout :set_contest_layout, only: [:show, :dashboard]

  def set_contest_task
    redirect_to contest_path(@contest)
    case params[:alter_to].to_i
      when 0
        flash[:notice] = "Contest tasks set to public."
      when 1
        flash[:notice] = "Contest tasks set to only visible during contest."
      when 2
        flash[:notice] = "Contest tasks set to invisible."
      else
        return
    end
    @tasks.map{|a| a.update(:visible_state => params[:alter_to].to_i)}
  end
  
  def dashboard
    if Time.now < @contest.start_time
      authenticate_admin!
    end

    c_submissions = nil
    if @contest.contest_type == 1 and Time.now >= @contest.start_time and Time.now <= @contest.end_time
      authenticate_user!
      if not current_user.admin?
        c_submissions = @contest.submissions.where("user_id = ?", current_user.id)
        flash[:notice] = "You can only see your own score."
      else
        c_submissions = @contest.submissions
      end
    else
      c_submissions = @contest.submissions
    end
    
    @submissions = []
    @participants = []
    @tasks.each_with_index do |task, index|
      @submissions << c_submissions.where("problem_id = ?", task.id)
      @participants = @participants | @submissions[index].map{|e| e.user_id}
    end
    @scores = []
    if @contest.contest_type == 2
      #penalty
      @participants.each do |u|
        t = []
        total_attm = 0
        total_solv = 0
        penalty = 0
        (0..(@tasks.size-1)).each do |index|
          succ = @submissions[index].select{|a| a.user_id == u and a.result == 'AC'}.min_by{|a| a.id}
          if succ
            attm = @submissions[index].select{|a| a.user_id == u and a.id < succ.id}.size
            t << [attm+1, (succ.created_at - @contest.start_time).to_i / 60]
            total_solv += 1
            total_attm += attm+1
            penalty += attm * 20
          else
            attm = @submissions[index].select{|a| a.user_id == u}.size
            t << [attm, 0]
            total_attm += attm
          end
        end
        @scores << [u, total_attm, total_solv, t, t.map{|a| a[1]}.sum + penalty]
      end
      @scores = @scores.sort{|a, b| a[2] != b[2] ? -(a[2] <=> b[2]) : a[4] <=> b[4]}
      @color = @scores.map{|a| a[2]}.uniq.sort_by{|a| -a}
      @color << 0
    else
      @participants.each do |u|
        t = []
        (0..(@tasks.size-1)).each do |index|
          if @submissions[index].select{|a| a.user_id == u}.empty?
            t << 0
          else
            t << @submissions[index].select{|a| a.user_id == u}.max_by{|a| a.score}.score
          end
        end
        @scores << [u, t, t.sum]
      end
      @scores = @scores.sort_by{|a| -a[2]}
      @color = @scores.map{|a| a[2]}.uniq.sort_by{|a| -a}
      @color << 0
    end

    set_page_title ("Dashboard - " + @contest.title)
  end

  def index
    @contests = Contest.order("id DESC").page(params[:page])
    set_page_title "Contests"
  end

  def show
    if Time.now < @contest.start_time
      unless user_signed_in? and current_user.admin?
        flash[:notice] = 'Contest has not yet started.'
        redirect_to action:'index'
        return
      end
    end
    set_page_title @contest.title
  end

  def new
    @contest = Contest.new
    3.times { @contest.contest_problem_joints.build }
    set_page_title "New contest"
  end

  def edit
    set_page_title ("Edit contest - " + @contest.title)
  end

  def create
    @contest = Contest.new(contest_params)
    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contest }
      else
        format.html { render action: 'new' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end

  private
  def set_contest
    @contest = Contest.find(params[:id])
  end
  
  def set_tasks
    @tasks = @contest.contest_problem_joints.order("id ASC").map{|e| e.problem}
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contest_params
    params.require(:contest).permit(
      :id,
      :title,
      :description,
      :start_time,
      :end_time,
      :contest_type,
      contest_problem_joints_attributes: 
      [
        :id,
        :problem_id,
        :_destroy
      ]
    )
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_contest_type_chooser.html.erb
<%= f.label :contest_type %><br>
<%= f.select :contest_type, [
["[0]gcj style (partial/dashboard)", "0"], 
["[1]ioi style (partial/no dashboard)", "1"], 
["[2]acm style (no partial/dashboard)", "2"]
], {}, {:class => 'form-control flat'} %>

app/views/contests/_form.html.erb
<%= nested_form_for(@contest) do |f| %>
   <% if @contest.errors.any? %>
       <div id="error_explanation">
       <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

       <ul>
          <% @contest.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
          <% end %>
       </ul>
       </div>
   <% end %>

   <div class="form-group">
       <%= render 'contest_type_chooser', :f => f %>
   </div>
   
   <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, :class => 'form-control flat' %>
   </div>
   
   <div class="form-group">
       <%= f.label :description %>
       <%= f.text_area :description, :class => 'form-control flat', :rows => "9" %>
   </div>
   
   <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <strong>Oh Geez! </strong><%= "If datetime picker isn't available, an example time format is `1996-12-19T16:39:57`." %>
  </div>
   <div class="form-group">
       <%= f.label :start_time %>
       <%= f.datetime_local_field :start_time, :class => 'form-control flat', :type => 'datetime-local' %>
   </div>
   
   <div class="form-group">
       <%= f.label :end_time %>
       <%= f.datetime_local_field :end_time, :class => 'form-control flat', :type => 'datetime-local' %>
   </div>

   <div class="alert alert-success alert-dismissible" role="alert">
     <button type="button" class="close" data-dismiss="alert">
       <span aria-hidden="true">&times;</span>
       <span class="sr-only">Close</span>
     </button>
     <strong>Oh Geez! </strong> <%= "Make sure tasks are set to `visible during contest`." %>
   </div>
   
   <%= f.fields_for :contest_problem_joints do |t| %>
     <div class="form-group">
       <div class="row">
         <div class="col-md-1">
          <%= t.label :task %>
         </div>
         <div class="col-md-2">
          <%= t.number_field :problem_id, :class => 'form-control flat', :autocomplete => "off" %>
         </div>
         <div class="col-md-3">
          <%= t.link_to_remove "Remove this task", :class => "btn btn-danger" %>
         </div>
       
       </div>
     </div>
   <% end %>
   <%= f.link_to_add "Add a task", :contest_problem_joints, :class => "btn btn-warning" %>
   
   <hr>
   
   <div class="actions">
       <%= f.submit :class => "btn btn-success btn-lg"%>
   </div>
<% end %>

app/views/contests/dashboard.html.erb
<h4 class="page-header">
  Dashboard <small><%= @contest.title %></small>
</h4>

<div class="row">
  <div class="col-md-2">
    <%= link_to 'Back to Contest', contest_path(@contest), :class => 'btn btn-default btn-xs btn-block' %>
  </div>
  <div class="col-md-2">
    <%= link_to 'Submissions', contest_submissions_path(@contest), :class => 'btn btn-info btn-xs btn-block' %>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Rank</th>
      <th></th>
      <th>Username</th>
      <th>Nickname</th>
      <% @tasks.each_with_index do |task, index| %>
	<th><%= link_to ('p' + (65+index).chr), contest_problem_path(@contest, task) %></th>
      <% end %>
      <% if @contest.contest_type == 2 %>
        <th>Att/Solv</th>
        <th>Penalty</th>
      <% else %>
        <th>Total</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @scores.each_with_index do |s, index| %>
      <% case s[2] %>
      <% when @color[0] %>
        <tr class="warning">
      <% when @color[1] %>
        <tr class="success">
      <% when @color[2] %>
        <tr class="info">
      <% else %>
        <tr>
      <% end %>
        <td><%= index+1 %></td>
        <td><%= link_to image_tag(User.find(s[0]).avatar.mini_thumb.to_s, :class => "img-rounded"), user_path(s[0]) %></td>
        <td><%= link_to User.find(s[0]).username, user_path(s[0]) %></td>
        <td><%= User.find(s[0]).nickname %></td>
        <% if @contest.contest_type == 2 %>
          <% s[3].each do |t|%>
            <td><%= t[0].to_s + "/" + t[1].to_s %></td>
          <% end %>
          <td><%= s[1].to_s + "/" + s[2].to_s %></td>
          <td><%= s[4] %></td>
        <% else %>
          <% s[1].each do |t|%>
            <td><%= t %></td>
          <% end %>
          <td><%= s[2] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-md-2">
    <%= link_to 'Back to Contest', contest_path(@contest), :class => 'btn btn-default btn-xs btn-block' %>
  </div>
  <div class="col-md-2">
    <%= link_to 'Submissions', contest_submissions_path(@contest), :class => 'btn btn-info btn-xs btn-block' %>
  </div>
</div>

app/views/contests/edit.html.erb
<h4 class="page-header">Editing contest</h4>

<%= render 'form' %>

<%= link_to 'Show Contest', @contest, :class => 'btn btn-primary btn-xs' %>
<%= link_to 'Back to Contests List', contests_path, :class => 'btn btn-default btn-xs' %>

app/views/contests/index.html.erb
<h4 class="page-header">Contests</h4>

<% if user_signed_in? && current_user.admin == true %>
  <%= link_to 'New Contest', new_contest_path, :class => 'btn btn-success btn-sm' %>
  <br>
<% end %>
<%= paginate @contests %>
<table class="table table-hover table-condensed table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th>Status</th>
      <% if user_signed_in? %>
      <% end %>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Contest Type</th>
      <% if user_signed_in? && current_user.admin == true %>
	<th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.title %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Particapate', contest, :class => 'btn btn-xs btn-primary', :target => '_blank' %></td>
        <% else %>
          <td></td>
        <% end %>
        <% if Time.now > contest.end_time %>
	  <td>Ended</td>
        <% elsif Time.now > contest.start_time %>
	  <td>Ready</td>
	<% else %>
	  <td>Not yet</td>
        <% end %>
        <td><%= contest.start_time.to_s(:clean) %></td>
        <td><%= contest.end_time.to_s(:clean) %></td>
        <% if contest.contest_type == 0 %>
	  <td>gcj style</td>
	<% elsif contest.contest_type == 1 %>
	  <td>ioi style</td>
	<% elsif contest.contest_type == 2 %>
	  <td>acm style</td>
	<% else %>
	  <td>wtf</td>
	<% end %>
        <% if user_signed_in? && current_user.admin == true %>
	  <td>
            <%= link_to 'Edit', edit_contest_path(contest), :class => 'btn btn-info btn-xs' %>
            <%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @contests %>

app/views/contests/new.html.erb
<h4 class="page-header">New contest</h4>

<%= render 'form' %>

<%= link_to 'Back to Contests List', contests_path, :class => 'btn btn-default btn-xs' %>

app/views/contests/show.html.erb
<h4 class='page-header'>
  Contest Name : <%= @contest.title %>
</h4>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">Starts at</h1>
      </div>
      <div class="panel-body">
        <%= @contest.start_time.to_s(:clean) %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">Ends at</h1>
      </div>
      <div class="panel-body">
        <%= @contest.end_time.to_s(:clean) %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">Contest Type</h1>
      </div>
      <div class="panel-body">
        <% case @contest.contest_type %>
        <% when 0 %>
          gcj style (partial/dashboard)
        <% when 1 %>
          ioi style (partial/no dashboard)
        <% when 2 %>
          acm style (no partial/dashboard)
        <% else %>
          wtf
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Description</h1>
  </div>
  <div class="panel-body">
    <%= markdown(@contest.description) %>
  </div>
</div>

<% if user_signed_in? and current_user.admin? %>
  <%= link_to "Set contest tasks to public", set_contest_task_path(@contest, "0"), :class => "btn btn-xs btn-inverse" %>
  <%= link_to "Set contest tasks to only visible during contest", set_contest_task_path(@contest, "1"), :class => "btn btn-xs btn-inverse" %>
  <%= link_to "Set contest tasks to invisible", set_contest_task_path(@contest, "2"), :class => "btn btn-xs btn-inverse" %>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Tasks</h1>
  </div>
  <div class="panel-body">
    <% @tasks.each_with_index do |task, index| %>
      <%= link_to ('p' + (65+index).chr + ' ' + task.id.to_s + '. ' + Problem.find(task.id).name), contest_problem_path(@contest, task.id) %>
      <br>
    <% end %>
  </div>
</div>

<p>
  <%= link_to 'Dashboard', {:controller => :contests, :action => :dashboard, :id => @contest.id}, {:class => 'btn btn-xs btn-warning'} %>
  <%= link_to 'Submissions', contest_submissions_path(@contest), :class => 'btn btn-info btn-xs' %>
  <% if user_signed_in? and current_user.admin? %>
    <%= link_to 'Edit', edit_contest_path(@contest), :class => 'btn btn-info btn-xs' %>
  <% end %>
  <%= link_to 'Back to Contests List', contests_path, :class => 'btn btn-default btn-xs' %>
</p>