config/routes.rb
Tioj::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :problems do
    resources :testdata
    resources :submissions
    resources :posts 
  end

  resources :judge_servers
  resources :submissions
  resources :users
  resources :posts do 
    resources :comments
  end
  
  resources :contests do
    resources :submissions
    resources :problems
  end
  resources :contest_problem_joints
  
  resources :articles
  
  get 'problems/tag/:tag' => 'problems#index', as: :problems_tag
  get 'problems/:id/ranklist' => 'problems#ranklist', as: :problem_ranklist
  
  get 'contests/:id/set_contest_task/:alter_to' => 'contests#set_contest_task', as: :set_contest_task
  get 'contests/:id/dashboard' => 'contests#dashboard'
  get 'submissions/:id/rejudge' => 'submissions#rejudge'
  get 'problems/:problem_id/rejudge' => 'submissions#rejudge_problem', as: :problem_rejudge
  
  get 'fetch/sjcode' => 'fetch#sjcode'
  get 'fetch/code' => 'fetch#code'
  get 'fetch/interlib' => 'fetch#interlib'
  get 'fetch/testdata' => 'fetch#testdata'
  get 'fetch/submission' => 'fetch#submission'
  get 'fetch/validating' => 'fetch#validating'
  get 'fetch/write_result' => 'fetch#write_result'
  post 'fetch/write_message' => 'fetch#write_message'
  get 'fetch/testdata_limit' => 'fetch#testdata_limit'
  get 'fetch/testdata_meta' => 'fetch#testdata_meta'
  
  mathjax 'mathjax'
  
  get 'edit_announcement' => 'welcome#edit_announcement', as: :edit_announcement
  post 'alter_announcement' => 'welcome#alter_announcement', as: :alter_announcement
  get 'about' => 'about#index', as: :about

  get 'problems/:id/*file' => redirect{ |path, req| "/#{path[:file]}"}, :format => false, :id => /[0-9]+/
  get 'problems/*file' => redirect{ |path, req| "/#{path[:file]}"}, :format => false

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @bulletins = Article.order("id DESC").where(pinned: 1).limit(5)
    @bulletins = @bulletins + Article.order("id DESC").where(pinned: 0).limit(5 - @bulletins.size)
    @contests = Contest.order("id DESC").limit(3)
    @users = get_sorted_user.take(10)
  end
  
  def edit_announcement
    authenticate_admin!
  end
  
  def alter_announcement
    authenticate_admin!
    anno = {:name => params[:name].to_s, :message => params[:message].to_s}
    File.open("public/announcement/anno", "w") do |f|
      f.write(anno.to_json)
    end
    redirect_to root_path
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/edit_announcement.html.erb
<%= form_tag(alter_announcement_path, :method => :post, :class => "form-inline") do %>
  <div class="form-group">
    <%= label_tag(:name) %>
    <%= text_field_tag(:name, nil, :class => "form-control input-sm flat") %>
  </div>
  <div class="form-group">
    <%= label_tag(:message) %>
    <%= text_field_tag(:message, nil, :class => "form-control input-sm flat") %>
  </div>
  <%= submit_tag("Submit", :class => "btn btn-success btn-xs") %>
<% end %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    <% if user_signed_in? and current_user.admin? %>
      <div>
        <%= link_to "Alter Announcement", edit_announcement_path, :class => "btn btn-info btn-xs" %>
      </div>
    <% end %>
    <div class="well well-lg">
      <h5>Bulletin Board<small class="pull-right"><%= link_to "Show all", articles_path %></small></h5>
      <%= render 'articles/table', :articles => @bulletins %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well well-lg">
      <h5>Recent Contests<small class="pull-right"><%= link_to "Show all", contests_path %></small></h5>
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th></th>
            <th>Status</th>
            <% if user_signed_in? %>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @contests.each do |f| %>
            <tr>
              <td><%= f.title %></td>
              <% if user_signed_in? %>
                <td><%= link_to 'Particapate', f, :class => 'btn btn-xs btn-primary', :target => '_blank' %></td>
              <% end %>
              <% if Time.now > f.end_time %>
                <td>Ended</td>
                <td><%= distance_of_time_in_words_to_now(f.end_time) + " ago" %></td>
              <% elsif Time.now > f.start_time %>
                <td>Ready</td>
                <td>Now</td>
              <% else %>
                <td>Not yet</td>
                <td><%= distance_of_time_in_words_to_now(f.start_time) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well well-lg">
      <h5>Ranked Coders<small class="pull-right"><%= link_to "Show all", users_path %></small></h5>
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Rank</th>
            <th></th>
            <th>Username</th>
            <th>Accepted</th>
            <th>AC Ratio</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each_with_index do |f, idx| %>
	      <tr>
              <td><%= idx + 1 %></td>
              <td><%= link_to image_tag(f.avatar.mini_thumb.to_s, :class => "img-rounded"), {:controller => 'users', :action => :show, :id => f.id} %></td>
              <td><%= link_to f.username, user_path(f) %></td>
              <td><%= f.ac %></td>
              <td><%= ac_ratio_by_user_with_infor(f) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>