config/routes.rb
Tioj::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :problems do
    resources :testdata
    resources :submissions
    resources :posts 
  end

  resources :judge_servers
  resources :submissions
  resources :users
  resources :posts do 
    resources :comments
  end
  
  resources :contests do
    resources :submissions
    resources :problems
  end
  resources :contest_problem_joints
  
  resources :articles
  
  get 'problems/tag/:tag' => 'problems#index', as: :problems_tag
  get 'problems/:id/ranklist' => 'problems#ranklist', as: :problem_ranklist
  
  get 'contests/:id/set_contest_task/:alter_to' => 'contests#set_contest_task', as: :set_contest_task
  get 'contests/:id/dashboard' => 'contests#dashboard'
  get 'submissions/:id/rejudge' => 'submissions#rejudge'
  get 'problems/:problem_id/rejudge' => 'submissions#rejudge_problem', as: :problem_rejudge
  
  get 'fetch/sjcode' => 'fetch#sjcode'
  get 'fetch/code' => 'fetch#code'
  get 'fetch/interlib' => 'fetch#interlib'
  get 'fetch/testdata' => 'fetch#testdata'
  get 'fetch/submission' => 'fetch#submission'
  get 'fetch/validating' => 'fetch#validating'
  get 'fetch/write_result' => 'fetch#write_result'
  post 'fetch/write_message' => 'fetch#write_message'
  get 'fetch/testdata_limit' => 'fetch#testdata_limit'
  get 'fetch/testdata_meta' => 'fetch#testdata_meta'
  
  mathjax 'mathjax'
  
  get 'edit_announcement' => 'welcome#edit_announcement', as: :edit_announcement
  post 'alter_announcement' => 'welcome#alter_announcement', as: :alter_announcement
  get 'about' => 'about#index', as: :about

  get 'problems/:id/*file' => redirect{ |path, req| "/#{path[:file]}"}, :format => false, :id => /[0-9]+/
  get 'problems/*file' => redirect{ |path, req| "/#{path[:file]}"}, :format => false

  root 'welcome#index'

end

app/models/submission.rb
# == Schema Information
#
# Table name: submissions
#
#  id           :integer          not null, primary key
#  code         :text(16777215)
#  compiler     :string(255)      default("")
#  result       :string(255)      default("queued")
#  score        :integer          default(0)
#  created_at   :datetime
#  updated_at   :datetime
#  problem_id   :integer          default(0)
#  user_id      :integer          default(0)
#  contest_id   :integer
#  _result      :text(65535)
#  total_time   :integer
#  total_memory :integer
#  message      :text(65535)
#

class Submission < ActiveRecord::Base
  belongs_to :problem
  belongs_to :user
  belongs_to :contest
  
  validates_length_of :code, :in => 0..5000000
  validates_length_of :message, :in => 0..65000, :allow_nil => true
  validates_inclusion_of :compiler, :in => %w(c++17 c++14 c++11 c++98 c11 c99 c90 haskell python2 python3)
  validates_inclusion_of :compiler, :in => %w(c++17 c++14 c++11 c++98 c11 c99 c90), 
    :message => "only c/c++ are allowed during contest",
    :if => :contest?

  def contest?
    contest_id != nil
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authenticate_admin!, except: [:index, :show, :create, :new]
  before_action :set_submissions
  before_action :set_submission, only: [:rejudge, :show, :edit, :update, :destroy]
  before_filter :set_contest, only: [:show]
  layout :set_contest_layout, only: [:show, :index, :new]
  
  def rejudge_problem
    Submission.where("problem_id = ?", params[:problem_id]).update_all(:result => "queued", :score => 0, :_result => "", :total_time => nil, :total_memory => nil)
    redirect_to :back
  end
  
  def rejudge
    @submission.update(:result => "queued", :score => 0, :_result => "", :total_time => nil, :total_memory => nil)
    redirect_to :back
  end
  
  def index
    @submissions = @submissions.order("id DESC").page(params[:page])
    set_page_title "Submissions"
  end

  def show
    unless (user_signed_in? and current_user.admin?) or (user_signed_in? and current_user.id == @submission.user_id)
      if @submission.contest && Time.now >= @submission.contest.start_time && Time.now <= @submission.contest.end_time
        if (not user_signed_in?) or (user_signed_in? and current_user.id != @submission.contest.user_id)
          redirect_to contest_path(@submission.contest), :notice => 'Submission is censored during contest.'
          return
        end
      end
    end
    @_result = @submission._result.to_s.split("/")
    set_page_title "Submission - " + @submission.id.to_s
  end

  def new
    if params[:problem_id].blank?
      redirect_to action:'index'
      return
    end
    unless current_user.admin?
      if @problem.visible_state == 2
        redirect_to action:'index'
        return
      elsif @problem.visible_state == 1
        if params[:contest_id].blank?
          redirect_to action:'index'
          return
        end
	contest = Contest.find(params[:contest_id])
        unless contest.problem_ids.include?(@problem.id) and Time.now >= contest.start_time and Time.now <= contest.end_time
          redirect_to problem_path(@problem), notice: 'Contest ended, cannot submit.'
          return
        end
      end
    end
    @submission = Submission.new
    @contest_id = params[:contest_id]
    set_page_title "New Submission - " + @problem.id.to_s + " - " + @problem.name
  end
  
  def create
    if not current_user.last_submit_time.blank? and Time.now - current_user.last_submit_time < 15
      redirect_to submissions_path, alert: 'CD time 15 seconds.'
      return
    end
    User.transaction do
      user = User.lock("LOCK IN SHARE MODE").find(current_user.id)
      if not user.update(:last_submit_time => Time.now)
        redirect_to submissions_path, alert: 'CD time 15 seconds.'
        return
      end
    end
    
    if params[:problem_id].blank?
      redirect_to action:'index'
      return
    end
    unless current_user.admin?
      if @problem.visible_state == 2
        redirect_to action:'index'
        return
      elsif @problem.visible_state == 1
        if params[:contest_id].blank?
          redirect_to action:'index'
          return
        end
        contest = Contest.find(params[:contest_id])
        unless contest.problem_ids.include?(@problem.id) and Time.now >= contest.start_time and Time.now <= contest.end_time
          redirect_to problem_path(@problem), notice: 'Contest ended, cannot submit.'
          return
        end
      end
    end
    
    #@submission = @submissions.build(submission_params)
    @submission = Submission.new(submission_params)
    @submission.user_id = current_user.id
    @submission.problem_id = params[:problem_id]
    if params[:contest_id]
      if @contest.problem_ids.include?(@submission.problem_id) and Time.now >= @contest.start_time and Time.now <= @contest.end_time
        @submission.contest_id = @contest.id
      end
    end
    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @submission }
      else
        format.html { render action: 'new' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    set_page_title "Edit submission - " + @submission.id.to_s
  end
  
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end
  
  private
  def set_submissions
    @problem = Problem.find(params[:problem_id]) if params[:problem_id]
    @contest = Contest.find(params[:contest_id]) if params[:contest_id]
    @submissions = Submission
    @submissions = @submissions.where("problem_id = ?", params[:problem_id]) if params[:problem_id]
    if params[:contest_id]
      @submissions = @submissions.where("contest_id = ?", params[:contest_id])
      unless user_signed_in? and current_user.admin?
        if Time.now <= @contest.end_time #and Time.now >= @contest.start_time
          #only self submission
          if user_signed_in?
            @submissions = @submissions.where("user_id = ?", current_user.id)
          else
            @submissions = @submissions.where("id = 0") #just make it a empty set whatsoever
            return
          end
        end
      end
    else
      #unless user_signed_in? and current_user.admin?
        @submissions = @submissions.where("contest_id is NULL")
      #end
    end
    @submissions = @submissions.where("problem_id = ?", params[:filter_problem]) if not params[:filter_problem].blank?
    @submissions = @submissions.joins("INNER JOIN users ON submissions.user_id = users.id").where("users.username LIKE ?", params[:filter_username]) if not params[:filter_username].blank?
    @submissions = @submissions.where("user_id = ?", params[:filter_user_id]) if not params[:filter_user_id].blank?
    @submissions = @submissions.where(result: params[:filter_status]) if not params[:filter_status].blank?
    @submissions = @submissions.where(compiler: params[:filter_compiler]) if not params[:filter_compiler].blank?
  end
  
  def set_submission
    @submission = Submission.find(params[:id])
  end
  
  def set_contest
    @contest = @submission.contest
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def submission_params
    params.require(:submission).permit(:code, :compiler, :problem_id)
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def censored(s)
    return false if user_signed_in? and current_user.admin?
    return false if user_signed_in? and current_user.id == s.user_id
    if s.contest && Time.now >= s.contest.start_time && Time.now <= s.contest.end_time
      return true if not user_signed_in?
      return true if user_signed_in? and current_user.id != s.user_id
    end
    return false
  end

  def language_class(lang)
    case lang
    when "c++17", "c++14", "c++11", "c++98", "c++"
      return "language-cpp"
    when "c11", "c99", "c90", "c"
      return "language-c"
    when "haskell"
      return "language-haskell"
    when "python2", "python3"
      return "language-python"
    else
      return "language-clike"
    end
  end
end

app/views/submissions/_compiler_chooser.html.erb
<%= f.label :compiler %>
<%= f.select :compiler, [
["c++14/gnu c++ compiler 7.2.0 | options: -O2 -std=c++14", "c++14"], 
["c++17/gnu c++ compiler 7.2.0 | options: -O2 -std=c++17", "c++17"], 
["c++11/gnu c++ compiler 7.2.0 | options: -O2 -std=c++11", "c++11"], 
["c++98/gnu c++ compiler 7.2.0 | options: -O2 -std=c++98", "c++98"], 
["c11/gnu c compiler 7.2.0 | options: -O2 -std=c11 -lm", "c11"],
["c99/gnu c compiler 7.2.0 | options: -O2 -std=c99 -lm", "c99"],
["c90/gnu c compiler 7.2.0 | options: -O2 -ansi -lm", "c90"],
["python2/CPython 2.7.6 | options: -m py_compile", "python2"],
["python3/CPython 3.6.4 | options: -m py_compile", "python3"],
["haskell/glasgow haskell compiler 7.8.3 with haskell platform | options: -O", "haskell"]
] , {}, {:class => 'form-control flat'} %>

app/views/submissions/_form.html.erb
<%= form_for [@problem, @submission] do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>
      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= render 'compiler_chooser', :f => f %>
  </div>
  
  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_area :code, :class => 'form-control flat', :rows => "15", :id => "code-input", style: 'font-family: Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace;' %>
  </div>
  
  <% if @contest_id %>
    <div class="field">
      <%= hidden_field_tag :contest_id, @contest_id %>
    </div>
  <% end %>
  
  <hr>
  
  <div class="actions">
    <%= f.submit :class => 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h4 class="page-header">Editing submission <small>#<%= @submission.id %></small></h4>

<%= render 'form' %>

<%= link_to 'Show Submission', @submission, :class => 'btn btn-primary btn-xs' %>
<%= link_to 'Back to Submissions List', submissions_path, :class => 'btn btn-default btn-xs' %>

app/views/submissions/index.html.erb
<h4 class="page-header">
  Submissions 
  <% if @problem %>
    <small>Problem #<%= @problem.id%></small>
  <% end %>
  <% if @contest %>
    <small>Contest #<%= @contest.id%></small>
  <% end %>
</h4>

<% if @problem %>
  <%= link_to 'Submit to Problem', new_problem_submission_path(@problem), :class => "btn btn-success btn-xs" %>
<% else %>
  <div class="form-inline">
    <div class="form-group">
      <label for="quick_prob_id">Quick Submit</label>
      <input style="width:150px" id="quick_prob_id" type="number" class="form-control input-sm flat" min="1" max="<%= Problem.count %>" placeholder="Enter Problem ID"/>
    </div>
    <button type="submit" id="quick_submit" class="btn btn-success btn-xs">Submit</button>
  </div>
<% end %>

<form class="form-inline" accept-charset="UTF-8" method="get">
  <label for="filter_user">Quick Filter</label>
  <div class="form-group">
    <input id="filter_username" name="filter_username" class="form-control input-sm flat" type="text" placeholder="Enter Username">
  </div>
  <div class="form-group">
    <input id="filter_problem" name="filter_problem" class="form-control input-sm flat" type="number" min="1" placeholder="Enter Problem ID">
  </div>
  <div class="form-group">
    <select id="filter_status" name="filter_status[]" class="selectpicker" multiple title="Select Result">
      <option value="AC">Accepted</option>
      <option value="WA">Wrong Answer</option>
      <option value="TLE">Time Limit Exceeded</option>
      <option value="MLE">Segmentation Fault</option>
      <option value="RE">Runtime Error</option>
      <option value="CE">Compilation Error</option>
    </select>
  </div>
  <div class="form-group">
    <select id="filter_compiler" name="filter_compiler[]" class="selectpicker" multiple="multiple" title="Select Compiler">
      <option value="c++17">c++17</option>
      <option value="c++14">c++14</option>
      <option value="c++11">c++11</option>
      <option value="c++98">c++98</option>
      <option value="c11">c11</option>
      <option value="c99">c99</option>
      <option value="c90">c90</option>
      <option value="python2">python2</option>
      <option value="python3">python3</option>
      <option value="haskell">haskell</option>
    </select>
  </div>
  <button type="submit" id="quick_filter" class="btn btn-inverse btn-xs">Filter</button>
</form>

<script>
$(".selectpicker").selectpicker({style: "form-control input-sm flat"});
</script>

<table class='table table-hover table-striped'>
  <thead>
    <tr>
      <th>#</th>
      <th>PID</th>
      <th>Submitter</th>
      <th>Time</th>
      <th>Memory</th>
      <th>Verdict</th>
      <th>Compiler</th>
      <th>Code Length</th>
      <th>Score</th>
      <th>Submit Time</th>
      <% if user_signed_in? && current_user.admin == true %>
         <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
      <% if censored(submission) %>
	<td></td>
        <td></td>
        <td><code>censored</code></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      <% else %>
        <td><%= link_to submission.id, submission_path(submission) %></td>
        <td>
          <% if submission.contest_id.blank? %>
            <%= link_to submission.problem_id, problem_path(submission.problem) %>
          <% else %>
            <%= link_to submission.problem_id, contest_problem_path(submission.contest_id, submission.problem) %>
          <% end %>
        </td>
        <td><%= link_to submission.user.nickname, user_path(submission.user) %></td>
        <td><%= submission.total_time.to_i %></td>
        <td><%= submission.total_memory.to_i %></td>
        <% case submission.result %>
          <% when "WA" %>
            <td class="text-danger">WA</td>
          <% when "TLE" %>
            <td class="text-info">TLE</td>
          <% when "MLE" %>
            <td class="text-warning">MLE</td>
          <% when "RE" %>
            <td class="text-warning">RE</td>
          <% when "AC" %>
            <td class="text-success">AC</td>
          <% when "queued" %>
            <td class="text-muted">queued</td>
          <% else %>
            <td><%= submission.result %></td>
        <% end %>
        <td><%= submission.compiler %></td>
        <td><%= number_to_human_size(submission.code.to_s.size) %></td>
        <td><%= submission.score %></td>
        <td><%= submission.created_at.to_s(:clean) %></td>
        <% if user_signed_in? && current_user.admin == true %>
	  <td>
            <%= link_to 'Rejudge', {:controller => :submissions, :action => :rejudge, :id => submission.id} , :class => 'btn btn-xs btn-primary' %>
          </td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @submissions %>

app/views/submissions/new.html.erb
<!--<%= javascript_include_tag 	"/stylesheets/prism.js" %>
<%= stylesheet_link_tag 	"/stylesheets/prism.css" %>-->
<h4 class="page-header">New submission <small><%= @problem.id %>. <%= @problem.name %><small></h4>

<%= render 'form' %>

<%= link_to 'Show Problem', problem_path(@problem), :class => 'btn btn-primary btn-xs' %>
<%= link_to 'Back to Submissions List', submissions_path, :class => 'btn btn-default btn-xs' %>

app/views/submissions/show.html.erb
<% if censored(@submission) %>
  <h4 class="page-header">Results of submission #<code>censored</code></h4>
  <code>censored</code>
<% else %>

<h4 class="page-header">Results of submission #<%= @submission.id %></h4>

<p>
<% if @contest.blank? %>
  <%= link_to 'Back to Submissions List', submissions_path, :class => 'btn btn-default btn-xs' %>
<% else %>
  <%= link_to 'Back to Submissions List', contest_submissions_path(@contest), :class => 'btn btn-default btn-xs' %>
<% end %>
<% if user_signed_in? and current_user.admin? %>
  <%= link_to 'Rejudge', { :controller => :submissions, :action => :rejudge, :id => @submission.id }, :class => 'btn btn-xs btn-primary' %>
  <%= link_to 'Edit', edit_submission_path(@submission), :class => 'btn btn-info btn-xs' %>
  <%= link_to 'Destroy', @submission, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-xs btn-danger' %>
<% end %>
</p>
<% case @submission.result %>
  <% when "WA" %>
    <div class="panel panel-danger">
  <% when "TLE" %>
    <div class="panel panel-info">
  <% when "MLE" %>
    <div class="panel panel-warning">
  <% when "RE" %>
    <div class="panel panel-warning">
  <% when "AC" %>
    <div class="panel panel-success">
  <% else %>
    <div class="panel panel-default">
<% end %>
  <div class="panel-heading">
  <div class="row">
    <div class="col-md-3">
      <h1 class="panel-title">Problem</h1>
    </div>
    <div class="col-md-2">
      <h1 class="panel-title">Total Time (ms)</h1>
    </div>
    <div class="col-md-2">
      <h1 class="panel-title">Max Memory (KiB)</h1>
    </div>
    <div class="col-md-3">
      <h1 class="panel-title">Verdict</h1>
    </div>
    <div class="col-md-2">
      <h1 class="panel-title">Score</h1>
    </div>
  </div>
  </div>
  <div class="panel-body">
  <div class="row">
    <div class="col-md-3">
      <% if @submission.contest_id.blank? %>
        <%= link_to @submission.problem.id.to_s + ". " + @submission.problem.name, problem_path(@submission.problem) %>
      <% else %>
        <%= link_to @submission.problem.id.to_s + ". " + @submission.problem.name, contest_problem_path(@submission.contest_id, @submission.problem) %>
      <% end %>
    </div>
    <div class="col-md-2">
      <%= @submission.total_time.to_i %>
    </div>
    <div class="col-md-2">
      <%= @submission.total_memory.to_i %>
    </div>
    <div class="col-md-3">
      <%= @verdict[@submission.result] %>
    </div>
    <div class="col-md-2">
      <%= @submission.score %>
    </div>
  </div>
  </div>
  
  <table class="table">
    <thead>
      <tr>
        <th>Testdata no.</th>
        <th>Time (ms)</th>
        <th>Memory (KiB)</th>
        <th>Verdict</th>
      </tr>
    </thead>
    <tbody>
      <% Range.new(0, @submission.problem.testdata.size - 1).each do |i| %>
        <tr>
          <td><%= i %></td>
          <td><%= @_result[i*3+1].to_i %></td>
          <td><%= @_result[i*3+2].to_i %></td>
          <td><%= @verdict[@_result[i*3]] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="well well-sm">
  <div class="row">
    <div class="col-md-2">
      <strong>Submitter:</strong>
    </div>
    <div class="col-md-2">
      <%= link_to @submission.user.username, user_path(@submission.user_id) %>
    </div>
    <div class="col-md-2">
      <strong>Compiler:</strong>
    </div>
    <div class="col-md-2">
      <%= @submission.compiler %>
    </div>
    <div class="col-md-2">
      <strong>Code Length:</strong>
    </div>
    <div class="col-md-2">
      <%= number_to_human_size(@submission.code.to_s.size) %>
    </div>
  </div>
</div>

<% if user_signed_in? and ( current_user.admin? or current_user.id == @submission.user_id ) %>
  <% if @submission.result == "CE" %>
    <div class="panel panel-default">
      <div class="panel-heading">
         <h1 class="panel-title">Compilation Error Message</h1>
      </div>
      <div class="panel-body">
        <% if @submission.message.present? %>
          <pre class="pre-scrollable"><code class=""><%= @submission.message %></code></pre>   
        <% else %>
          Sorry, no compilation error message available.
        <% end %>
      </div>
    </div>
  <% end %>
  <pre class="line-numbers"><code class="<%= language_class(@submission.compiler) %>"><%= @submission.code %></code></pre>
<% end %>

<%= link_to 'Back to Top', '#', :class => 'btn btn-default btn-xs' %>

<% end %>

<%= javascript_include_tag 	"/codehighlighter/prism.js" %>
<%= stylesheet_link_tag 	"/codehighlighter/prism.css" %>